<a href="https://colab.research.google.com/github/HarshiniArulmani2006/Harshini-codeboosters-2026/blob/main/Day_5/Day_5_data_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split   #sklearn ML library
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('All Libraries imported successfully!!!!')

All Libraries imported successfully!!!!

In [3]:
df=pd.read_csv('student_performance.csv')
print(f'Dataset Loaded:{df.shape[0]} students,{df.shape[1]} columns')
print(f'Columns:{df.columns.tolist()}')
print(f'\nMissing Values:{df.isnull().sum().sum()}')
print('\nFirst 5 rows:')
df.head()

Dataset Loaded:30 students,13 columns
Columns:['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

Missing Values:0

First 5 rows:

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [4]:
#predicting programming score
print(df['programming_score'].describe())

count    30.000000
mean     67.600000
std      21.041175
min      38.000000
25%      49.250000
50%      66.000000
75%      88.750000
max      97.000000
Name: programming_score, dtype: float64

In [5]:
#Male=0,Female=1 prediction of programming sccore
df_ml=df.copy()
le_gender=LabelEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])
print(f'Gender Encoding:{dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}')
#dict combining the result in dictionary
le_dept=LabelEncoder()
df_ml['department_encoded']=le_dept.fit_transform(df_ml['department'])
print(f'Department Encoding:{dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}')
print('\nNew Columns Added:gender_encoded,department_encoded')
df_ml[['gender','gender_encoded','department','department_encoded']].head(10)

Gender Encoding:{'Female': np.int64(0), 'Male': np.int64(1)}
Department Encoding:{'Civil': np.int64(0), 'Computer Science': np.int64(1), 'Electronics': np.int64(2), 'Mechanical': np.int64(3)}

New Columns Added:gender_encoded,department_encoded

   gender  gender_encoded        department  department_encoded
0    Male               1  Computer Science                   1
1  Female               0  Computer Science                   1
2    Male               1       Electronics                   2
3  Female               0        Mechanical                   3
4    Male               1  Computer Science                   1
5  Female               0       Electronics                   2
6    Male               1             Civil                   0
7  Female               0  Computer Science                   1
8    Male               1        Mechanical                   3
9  Female               0  Computer Science                   1

In [6]:
#select features and define target
feature_cols=[
    'math_score',
    'science_score',
    'english_score',
    'attendance_percentage',
    'gender_encoded',
    'department_encoded'
]
X=df_ml[feature_cols]
y=df_ml['programming_score']

print(f'Feature matrix X shape:{X.shape} (student x features)')
print(f'Target vector y shape:{y.shape} (one score per student)')
print(f'\n Feature Columns:{feature_cols}')
print(f'Target Column:programming_score')
print(f'\nTarget Score range:{y.min()} to {y.max()} (Mean:{y.mean():.1f})')

Feature matrix X shape:(30, 6) (student x features)
Target vector y shape:(30,) (one score per student)

 Feature Columns:['math_score', 'science_score', 'english_score', 'attendance_percentage', 'gender_encoded', 'department_encoded']
Target Column:programming_score

Target Score range:38 to 97 (Mean:67.6)

In [7]:
# Now ML working above next Train and Test Split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
    )
print(f'Total Students:{len(X)}')
print(f'Training Students:{len(X_train)}({len(X_train)/len(X)*100:.0f}%)')
print(f'Testing Students:{len(X_test)}({len(X_test)/len(X)*100:.0f}%)')
print(f'\nTraining Target Range:{y_train.min()} to {y_train.max()}')
print(f'Testing Target Range:{y_test.min()} to {y_test.max()}')

Total Students:30
Training Students:24(80%)
Testing Students:6(20%)

Training Target Range:38 to 96
Testing Target Range:39 to 97

In [8]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
print('Features scaled Successfully!!')
print(f'Training feature Mean(should be -0):{X_train_scaled.mean():.4f}')
print(f'Training feature Standard Deviation(should be -1):{X_train_scaled.std():.4f}')

Features scaled Successfully!!
Training feature Mean(should be -0):-0.0000
Training feature Standard Deviation(should be -1):1.0000

In [11]:
# for training the model ...... 1)linear Regression used
lr_model=LinearRegression()
lr_model.fit(X_train_scaled,y_train)
lr_pred=lr_model.predict(X_test_scaled)
#evaluate
lr_mae=mean_absolute_error(y_test,lr_pred)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
lr_r2=r2_score(y_test,lr_pred)

print(f'Linear Regression ')
print(f'MAE:{lr_mae:.2f} (predictions are off by {lr_mae:.1f} points on average)')
print(f'RMSE:{lr_rmse:.2f} (error with penality for large mistakes)')
print(f'R^2:{lr_r2:.4f}({lr_r2*100:.1f}% of progrmming score variation explained)')
print()
print('Learned coefficients (importance of each feature):')
for feat,coef in zip(feature_cols,lr_model.coef_):
    print(f'{feat:<28}:{coef:+.3f}')
print(f'{'bias(intercept)':<28}:{lr_model.intercept_:+.3f}')

Linear Regression
MAE:9.37 (predictions are off by 9.4 points on average)
RMSE:11.47 (error with penality for large mistakes)
R^2:0.7356(73.6% of progrmming score variation explained)

Learned coefficients (importance of each feature):
math_score                  :+20.256
science_score               :+7.612
english_score               :+2.396
attendance_percentage       :-12.886
gender_encoded              :-0.397
department_encoded          :-0.449
bias(intercept)             :+68.042

In [14]:
#2) Decision Tree to train the model
dt_model=DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)
dt_model.fit(X_train_scaled,y_train)
dt_pred=dt_model.predict(X_test_scaled)

dt_mae=mean_absolute_error(y_test,dt_pred)
dt_rmse=np.sqrt(mean_squared_error(y_test,dt_pred))
dt_r2=r2_score(y_test,dt_pred)

print(f'Decision Tree')
print(f'MAE: {dt_mae:.2f}')
print(f'RMSE: {dt_rmse:.2f}')
print(f'R^2: {dt_r2:.4f}')

Decision Tree
MAE: 10.75
RMSE: 16.08
R^2: 0.4803

In [15]:
#Random forest --it's more accurate
# 3) Random Forest to train the model
rf_model=RandomForestRegressor(
    n_estimators=100,
    max_depth=5,
    random_state=42
)
rf_model.fit(X_train_scaled, y_train)
rf_pred=rf_model.predict(X_test_scaled)
# Evaluate
rf_mae=mean_absolute_error(y_test, rf_pred)
rf_rmse=np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2=r2_score(y_test, rf_pred)
print('Random Forest')
print(f'MAE: {rf_mae:.2f}')
print(f'RMSE: {rf_rmse:.2f}')
print(f'R^2: {rf_r2:.4f}')

Random Forest
MAE: 10.59
RMSE: 14.03
R^2: 0.6043